version: '3.9'
services:
  todo-db:
    container_name: todo-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - todo-db-data:/var/lib/postgresql/data

volumes:
  todo-db-data:
